[package]
name = "asteroid-dodge"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.6"
glam = "0.18.0"
mint = "0.5.6"
rand = "0.8.4"
